---
title: "Module - Doublet Detection"
description: | 
  Description
execute:
  freeze: auto
  cache: false
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    embed-resources: true
    code-fold: show
    code-tools: true
    df-print: paged
    fig-format: png
    fig-dpi: 300
    fig-responsive: true
    fig-align: center
lightbox:
    match: auto
    effect: zoom
    loop: true
params:
  project_name: 'Project'
  seurat_object: './data/Test_main_cluster_object.RDS'
  n_threads: 8
  n_memory: 16
  work_directory: !expr here::here()
  auto_save: TRUE
---

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}
#| include: false

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds

# Optional parameters

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}
#| output: false

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(DT)
library(DoubletFinder)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/doublet')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

# Expanding memory
options(future.globals.maxSize = n_memory*1024^3)

```

## Input validation

```{r basic_input_validation}

# Checking assay version
assay_version <- class(seurat_object[["RNA"]])[1]

# Converting for Assay5
if(assay_version == "Assay5") {
  
  seurat_object[["RNA5"]] <- as(
    object = seurat_object[["RNA"]], Class = "Assay5")
  
  seurat_object[["RNA"]] <- as(
    object = seurat_object[["RNA"]], Class = "Assay")
  
}

```

## Clustering summary {.tabset}

```{r clustering_summary, fig.height = 12, fig.width = 14}
#| label: fig-violin
#| fig-width: 14
#| fig-height: 20
#| fig-align: center

DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    raster = FALSE,
    label.size = 12
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

## Running DoubleFinder

```{r finding_doublets}

double_annotation <- data.frame()
patient_list <- unique(seurat_object$patient_id)

for(patient in patient_list) {
  
  seurat_sample <- subset(
    seurat_object, subset = patient_id == patient)

  # Data preparation
  seurat_swep_list <- paramSweep_v3(seurat_sample, PCs = 1:10, sct = FALSE)
  seurat_swep_stats <- summarizeSweep(seurat_swep_list, GT = FALSE)
  seurat_find_pk <- find.pK(seurat_swep_stats)
  
  # Retrieve cluster annotation
  annotations <- seurat_sample@meta.data$seurat_clusters
  homotypic_prop <- modelHomotypic(annotations)

  # nExp
  nExp_poi <- round(0.075 * nrow(seurat_sample@meta.data))
  nExp_poi_adj <- round(nExp_poi*(1 - homotypic_prop))
  
  # Calculating doubletFinder
  seurat_sample <- doubletFinder_v3(
    seurat_sample, 
    PCs = 1:10, 
    pN = 0.25, 
    pK = 0.09, 
    nExp = nExp_poi, 
    reuse.pANN = FALSE, 
    sct = FALSE
  )
  
  # Renaming columns
  column_indexes <- sapply(c("pANN_", "DF.classifications_"), function(column) {
    grep(column, colnames(seurat_sample@meta.data))
  })
  
  colnames(seurat_sample@meta.data)[column_indexes] <- 
    c("pANN_score", "doublet_classification")

  double_annotation <- rbind(
    double_annotation,
    seurat_sample@meta.data
  )
  
}

```

```{r double_combine_metadata}

new_columns <- setdiff(
  colnames(double_annotation),
  colnames(seurat_object@meta.data)
)

seurat_object <- AddMetaData(
  seurat_object,
  metadata = double_annotation[, new_columns]
)

```

## Metadata Inspection

```{r meta_inspection}

datatable(seurat_object@meta.data, 
    class = 'cell-border stripe',
    rownames = FALSE,
    filter = 'top',
    width = '100%', 
    options = list(scrollX = TRUE)
    )

```

## Data Visualization

```{r cluster_composition}

# Retrieving cluster composition
seurat_cluster_composition <- seurat_object@meta.data %>%
  group_by(seurat_clusters, patient_id, doublet_classification) %>%
  summarise(
    n_doublet_per_patient = n()
  )

seurat_cluster_composition <- seurat_cluster_composition %>%
  group_by(seurat_clusters) %>%
  mutate(
    n_cells_per_cluster = sum(n_doublet_per_patient),
    percentage_doublets = round((n_doublet_per_patient*100) / n_cells_per_cluster, 2)
  )

# Remove singles 
seurat_doublet_quantification <- seurat_cluster_composition %>%
  filter(doublet_classification != 'Singlet')

# Dotplot Plot
ggplot(seurat_doublet_quantification, 
       aes(x = seurat_clusters, y = percentage_doublets, fill = patient_id)) +
  geom_col() +
  labs(x = "Seurat Clusters", y = "% of Doublets", fill = "Patient ID:") +
  theme_classic() +
  theme(
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 16),
    legend.position = "top"
  )

```

## Feature Plot

```{r}

DimPlot(
    seurat_object, 
    reduction = "umap",
    group.by = "doublet_classification",
    label = TRUE,
    raster = FALSE,
    label.size = 12
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```


## Saving Seurat object

```{r object_dump}

if(auto_save) {
  
  saveRDS(double_annotation, file = paste0('data/', project_name, '_doublet_table.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
