---
title: "Module - Rendering quality report"
description: | 
  Description
execute:
  freeze: auto
  cache: false
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    embed-resources: true
    code-fold: show
    code-tools: true
    df-print: paged
    fig-align: center
lightbox:
    match: auto
    effect: zoom
    loop: true
params:
  project_name: 'Test'
  input_metrics_report: './data/Test_metrics_report.csv'
  n_threads: 8
  n_memory: 16
  work_directory: !expr here::here()
  auto_save: TRUE
---


# Project Name: `r params$project_name`

```{r setup, message = FALSE, warning = FALSE, echo = TRUE}
#| include: false

# Project parameters 
project_name <- params$project_name
input_metrics_report <- strsplit(
  params$input_metrics_report, split = ';')[[1]]

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(
  root.dir = work_directory,
  error = TRUE
  )

```

## Loading library

```{r library, message = FALSE, warning = FALSE, echo = TRUE}
#| output: false
#| code-fold: true

library(readr)
library(dplyr)
library(ggplot2)
library(DT)

```

## Report interactive table

```{r merging_report, message = FALSE, warning = FALSE, echo = TRUE}
#| code-fold: true

metric_report_db <- data.frame()

for (sample_metric in input_metrics_report) {
  metric_report_tmp <- read_csv(file = sample_metric)
  metric_report_db <- rbind(
        metric_report_db,
        metric_report_tmp
    )

}

```

```{r}
#| column: screen-inset-shaded

DT::datatable(metric_report_db, 
    class = 'cell-border stripe',
    rownames = FALSE,
    filter = 'top',
    width = '100%', 
    options = list(scrollX = TRUE))

```

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = TRUE}
#| code-fold: true

print(
  list(
      project_name = project_name,
      input_metrics_report = input_metrics_report,
      work_directory = work_directory,
      auto_save = auto_save
  )
)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = TRUE}
#| code-fold: true

sessionInfo()

```
